stages:
  - test
  - build


.test_python:
  stage: test
  before_script:
    - pip install --upgrade Cython setuptools pip
    - git clone https://github.com/smok-serwis/minijson.git
    - cd minijson
    - python setup.py install
    - cd ..
    - rm -rf minijson
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace
  variables:
    CI: "1"
  script:
    - python -m coverage run -m nose2 -vv -F
    - python -m coverage report



test_python38:
  extends: .test_python
  image: python:3.8
