language: python
stages:
  - name: test
cache: pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - pip install -r requirements.txt
  - pip install -U nose2 coverage Cython satella snakehouse
  - python setup.py build_ext --inplace
jobs:
  include:
    - stage: test
      python: "3.5"
      script:
        - bash tests/test.sh
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.6"
      script:
        - bash tests/test.sh
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.7"
      script:
        - bash tests/test.sh
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.8"
      script:
        - bash tests/test.sh
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "3.9"
      script:
        - bash tests/test.sh
      after_script:
        - coverage xml
        - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
    - stage: test
      python: "pypy3.5"
      script:
        - bash tests/test.sh



